version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: gpthub-db
    restart: always
    environment:
      POSTGRES_DB:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gpthub_admin -d openwebui"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - gpthub-network

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    ports:
      - "3000:8080" 
    environment:
      - WEBUI_SECRET_KEY=
      - DATABASE_URL=
      - PIPELINES_URLS=http://pipelines:9099
      - ENABLE_SIGNUP=True
      - DEFAULT_MODELS=main
      - OPENAI_API_BASE_URL=
      - OPENAI_API_KEY=
    volumes:
      - open-webui-data:/app/backend/data
    depends_on:
      db:
        condition: service_healthy
      pipelines:
        condition: service_started  
    networks:
      - gpthub-network

  pipelines:
    image: ghcr.io/open-webui/pipelines:main
    container_name: pipelines
    restart: "no" 
    ports:
      - "9099:9099"
    environment:
      - PIPELINES_URL=http://pipelines:9099
      - PIPELINES_API_KEY=0000
      - MWS_API_KEY=
      - OPENAI_API_BASE_URL=
      - OPENAI_API_KEY=
      - PYTHONUNBUFFERED=1
    volumes:
      - ./pipelines_logic:/app/pipelines 
    entrypoint: 
      - /bin/sh
      - -c
      - |
        if [ -f /app/pipelines/requirements.txt ]; then
          pip install --no-cache-dir -r /app/pipelines/requirements.txt
        fi
        exec /app/start.sh
    networks:
      - gpthub-network

volumes:
  open-webui-data:
  postgres_data:

networks:
  gpthub-network:
    driver: bridge
